-- Create the table for storing offer registrations
create table public.offer_registrations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  full_name text not null,
  phone_number text not null
);

-- Set up Row Level Security (RLS)
alter table public.offer_registrations enable row level security;

-- Allow anonymous users to insert data (since we use anon key in the app)
create policy "Enable insert for everyone"
on public.offer_registrations
for insert
with check (true);

-- Allow anyone to read data (optional, remove if not needed)
create policy "Enable select for everyone"
on public.offer_registrations
for select
using (true);
